apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfixadmin-fetchmail.fullname" . }}
type: Opaque
stringData:

  {{/* SETUP CONFIG */}}
  {{ range $key, $value := .Values.config }}
  {{ upper $key}}: {{ quote $value }}
  {{ end }}
